id = "AssetOwner"
icon = "lucide/building-2.svg"
label.en = "Asset Owner"

[[card]]
query = "SELECT COUNT(*) FROM AssetOwner"
type = "integer"
label.en = "Elements"
unit.en = "asset owner(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the asset owner"

[[attribute]]
id = "price_type"
label.en = "Price Type"
tooltip.en = "Price type of the asset owner"

[[attribute]]
id = "risk_factor"
label.en = "Risk Factor"
tooltip.en = "Risk factor of the asset owner"

[[attribute_group]]
id = "markup"
label.en = "Markup"
icon = "lucide/circle-dollar-sign.svg"

[[attribute]]
id = "segment_fraction"
label.en = "Segment Fraction"
tooltip.en = "Segment fraction of the asset owner"
