id = "Configuration"
icon = "lucide/settings.svg"
label.en = "Configuration"

[[card]]
query = "SELECT initial_date_time FROM Configuration"
type = "datetime"
format = "yyyy-MM-dd"
label.en = "Initial Date"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the configuration"

[[attribute]]
id = "number_of_nodes"
label.en = "Nodes"
tooltip.en = "Number of nodes in the configuration"
hide = true

[[attribute]]
id = "number_of_subscenarios"
label.en = "Subscenarios"
tooltip.en = "Number of subscenarios in the configuration"
hide = true

[[attribute]]
id = "iteration_limit"
label.en = "Iteration Limit"
tooltip.en = "Iteration limit of the configuration"
hide = true

[[attribute]]
id = "initial_date_time"
label.en = "Initial Date Time"
tooltip.en = "Initial date time of the configuration"
unit = "yyyy-MM-dd HH:mm"
hide = true

[[attribute]]
id = "time_series_step"
label.en = "Time Series Step"
tooltip.en = "Time series step of the configuration"
hide = true

[[attribute]]
id = "hydro_balance_subperiod_resolution"
label.en = "Hydro Balance Subperiod Resolution"
tooltip.en = "Hydro balance subperiod resolution of the configuration"
hide = true

[[attribute]]
id = "loop_subperiods_for_thermal_constraints"
label.en = "Loop Subperiods for Thermal Constraints"
tooltip.en = "Loop subperiods for thermal constraints of the configuration"
hide = true

[[attribute]]
id = "cycle_discount_rate"
label.en = "Cycle Discount Rate"
tooltip.en = "Cycle discount rate of the configuration"
hide = true

[[attribute]]
id = "cycle_duration_in_hours"
label.en = "Cycle Duration in Hours"
tooltip.en = "Cycle duration in hours of the configuration"
hide = true

[[attribute]]
id = "hydro_minimum_outflow_violation_cost"
label.en = "Hydro Minimum Outflow Violation Cost"
tooltip.en = "Hydro minimum outflow violation cost of the configuration"
hide = true

[[attribute]]
id = "hydro_spillage_cost"
label.en = "Hydro Spillage Cost"
tooltip.en = "Hydro spillage cost of the configuration"
hide = true

[[attribute]]
id = "aggregate_buses_for_strategic_bidding"
label.en = "Aggregate Buses for Strategic Bidding"
tooltip.en = "Aggregate buses for strategic bidding of the configuration"
hide = true

[[attribute]]
id = "parp_max_lags"
label.en = "PARP Max Lags"
tooltip.en = "PARP max lags of the configuration"
hide = true

[[attribute]]
id = "bid_data_source"
type = "enum"
enum = "bid_data_source"
label.en = "Bid Data Source"
tooltip.en = "Bid data source of the configuration"
hide = true

[[attribute]]
id = "clearing_hydro_representation"
label.en = "Clearing Hydro Representation"
tooltip.en = "Clearing hydro representation of the configuration"
hide = true

[[attribute]]
id = "ex_post_physical_hydro_representation"
label.en = "Ex Post Physical Hydro Representation"
tooltip.en = "Ex post physical hydro representation of the configuration"
hide = true

[[attribute]]
id = "clearing_integer_variables"
label.en = "Clearing Integer Variables"
tooltip.en = "Clearing integer variables of the configuration"
hide = true

[[attribute]]
id = "settlement_type"
label.en = "Settlement Type"
tooltip.en = "Settlement type of the configuration"
hide = true

[[attribute]]
id = "make_whole_payments"
label.en = "Make Whole Payments"
tooltip.en = "Make whole payments of the configuration"
hide = true

[[attribute]]
id = "construction_type_ex_ante_physical"
label.en = "Construction Type Ex Ante Physical"
tooltip.en = "Construction type ex ante physical of the configuration"
hide = true

[[attribute]]
id = "construction_type_ex_ante_commercial"
label.en = "Construction Type Ex Ante Commercial"
tooltip.en = "Construction type ex ante commercial of the configuration"
hide = true

[[attribute]]
id = "construction_type_ex_post_physical"
label.en = "Construction Type Ex Post Physical"
tooltip.en = "Construction type ex post physical of the configuration"
hide = true

[[attribute]]
id = "construction_type_ex_post_commercial"
label.en = "Construction Type Ex Post Commercial"
tooltip.en = "Construction type ex post commercial of the configuration"
hide = true

[[attribute]]
id = "use_fcf_in_clearing"
type = "enum"
enum = "boolean"
label.en = "Use FCF in Clearing"
tooltip.en = "Use FCF in clearing of the configuration"
hide = true

[[attribute]]
id = "integer_variable_representation_ex_ante_physical"
label.en = "Integer Variable Representation Ex Ante Physical"
tooltip.en = "Integer variable representation ex ante physical of the configuration"
hide = true

[[attribute]]
id = "integer_variable_representation_ex_ante_commercial"
label.en = "Integer Variable Representation Ex Ante Commercial"
tooltip.en = "Integer variable representation ex ante commercial of the configuration"
hide = true

[[attribute]]
id = "integer_variable_representation_ex_post_physical"
label.en = "Integer Variable Representation Ex Post Physical"
tooltip.en = "Integer variable representation ex post physical of the configuration"
hide = true

[[attribute]]
id = "integer_variable_representation_ex_post_commercial"
label.en = "Integer Variable Representation Ex Post Commercial"
tooltip.en = "Integer variable representation ex post commercial of the configuration"
hide = true

[[attribute]]
id = "spot_price_floor"
label.en = "Spot Price Floor"
tooltip.en = "Spot price floor of the configuration"
hide = true

[[attribute]]
id = "spot_price_cap"
label.en = "Spot Price Cap"
tooltip.en = "Spot price cap of the configuration"
hide = true

[[attribute]]
id = "virtual_reservoir_correspondence_type"
label.en = "Virtual Reservoir Correspondence Type"
tooltip.en = "Virtual reservoir correspondence type of the configuration"
hide = true

[[attribute]]
id = "vr_curveguide_data_source"
type = "enum"
enum = "vr_curveguide_data_source"
label.en = "VR Curveguide Data Source"
tooltip.en = "VR curveguide data source of the configuration"
hide = true

[[attribute]]
id = "vr_curveguide_data_format"
type = "enum"
enum = "vr_curveguide_data_format"
label.en = "VR Curveguide Data Format"
tooltip.en = "VR curveguide data format of the configuration"
hide = true

[[attribute]]
id = "number_of_periods"
label.en = "Periods"
tooltip.en = "Number of periods in the configuration"

[[attribute]]
id = "number_of_scenarios"
label.en = "Scenarios"
tooltip.en = "Number of scenarios in the configuration"

[[attribute]]
id = "number_of_subperiods"
label.en = "Subperiods"
tooltip.en = "Number of subperiods in the configuration"
hide = true

[[attribute]]
id = "demand_deficit_cost"
label.en = "Demand Deficit Cost"
tooltip.en = "Demand deficit cost of the configuration"
hide = true

[[attribute]]
id = "policy_graph_type"
type = "enum"
enum = "policy_graph_type"
label.en = "Policy Graph Type"
tooltip.en = "Policy graph type of the configuration"
hide = true

[[attribute]]
id = "renewable_scenarios_files"
type = "enum"
enum = "uncertainty_scenarios_files"
label.en = "Renewable Scenarios Files"
tooltip.en = "Renewable scenarios files of the configuration"
hide = true

[[attribute]]
id = "inflow_scenarios_files"
type = "enum"
enum = "uncertainty_scenarios_files"
label.en = "Inflow Scenarios Files"
tooltip.en = "Inflow scenarios files of the configuration"
hide = true

[[attribute]]
id = "demand_scenarios_files"
type = "enum"
enum = "uncertainty_scenarios_files"
label.en = "Demand Scenarios Files"
tooltip.en = "Demand scenarios files of the configuration"
hide = true

[[attribute]]
id = "market_clearing_tiebreaker_weight"
label.en = "Market Clearing Tiebreaker Weight"
tooltip.en = "Market clearing tiebreaker weight of the configuration"
hide = true

[[attribute]]
id = "integer_variable_representation_mincost"
label.en = "Integer Variable Representation Min Cost"
tooltip.en = "Integer variable representation min cost of the configuration"
hide = true

[[attribute]]
id = "network_representation_mincost"
label.en = "Network Representation Min Cost"
tooltip.en = "Network representation min cost of the configuration"
hide = true

[[attribute]]
id = "network_representation_ex_ante_physical"
type = "enum"
enum = "network_representation"
label.en = "Network Representation Ex Ante Physical"
tooltip.en = "Network representation ex ante physical of the configuration"
hide = true

[[attribute]]
id = "network_representation_ex_ante_commercial"
type = "enum"
enum = "network_representation"
label.en = "Network Representation Ex Ante Commercial"
tooltip.en = "Network representation ex ante commercial of the configuration"
hide = true

[[attribute]]
id = "network_representation_ex_post_physical"
type = "enum"
enum = "network_representation"
label.en = "Network Representation Ex Post Physical"
tooltip.en = "Network representation ex post physical of the configuration"
hide = true

[[attribute]]
id = "network_representation_ex_post_commercial"
label.en = "Network Representation Ex Post Commercial"
type = "enum"
enum = "network_representation"
tooltip.en = "Network representation ex post commercial of the configuration"
hide = true

[[attribute_group]]
id = "subperiod_duration"
label.en = "Subperiod Duration"
icon = "lucide/clock.svg"

[[attribute]]
id = "subperiod_duration_in_hours"
label.en = "Subperiod Duration in Hours"
tooltip.en = "Subperiod duration in hours of the configuration"

[[attribute_group]]
id = "expected_number_of_repeats_per_node"
label.en = "Number of Repeats"
icon = "lucide/repeat.svg"

[[attribute]]
id = "expected_number_of_repeats_per_node"
label.en = "Expected Number of Repeats per Node"
tooltip.en = "Expected number of repeats per node of the configuration"

[[attribute]]
id = "hour_subperiod_map"
label.en = "Hour Subperiod Map"
tooltip.en = "Mapping of hours to subperiods"
hide = true

[[attribute]]
id = "fcf_cuts"
label.en = "FCF Cuts"
tooltip.en = "FCF cuts for the model, it's a file read from SDDP.jl in JSON format"
hide = true

[[attribute]]
id = "period_season_map"
label.en = "Period Season Map"
tooltip.en = "Mapping of periods to seasons"
hide = true