[[boolean]]
id = 0
label.en = "False"

[[boolean]]
id = 1
label.en = "True"

[[existing]]
id = 0
label.en = "Does Not Exist"

[[existing]]
id = 1
label.en = "Exists"

[[has_commitment]]
id = 0
label.en = "No Commitment"

[[has_commitment]]
id = 1
label.en = "Has Commitment"

[[policy_graph_type]]
id = 0
label.en = "Cyclic With Null Root"

[[policy_graph_type]]
id = 1
label.en = "Linear"

[[policy_graph_type]]
id = 2
label.en = "Cyclic With Season Root"

[[time_series_step]]
id = 0
label.en = "One Month Per Period"

[[hydro_balance_subperiod_resolution]]
id = 0
label.en = "Chronological Subperiods"

[[hydro_balance_subperiod_resolution]]
id = 1
label.en = "Aggregated Subperiods"

[[variable_aggregation_type]]
id = 0
label.en = "Sum"

[[variable_aggregation_type]]
id = 1
label.en = "Average"

[[variable_aggregation_type]]
id = 2
label.en = "Last Value"

[[bid_data_processing]]
id = 0
label.en = "Read From File"

[[bid_data_processing]]
id = 1
label.en = "Price Taker Heuristics"

[[clearing_hydro_representation]]
id = 0
label.en = "Pure Bids"

[[clearing_hydro_representation]]
id = 1
label.en = "Virtual Reservoirs"

[[integer_variable_representation]]
id = 0
label.en = "Calculate Normally"

[[integer_variable_representation]]
id = 1
label.en = "From Ex Ante Physical"

[[integer_variable_representation]]
id = 2
label.en = "Linearize"

[[construction_type]]
id = -1
label.en = "Skip"

[[construction_type]]
id = 0
label.en = "Cost Based"

[[construction_type]]
id = 1
label.en = "Bid Based"

[[construction_type]]
id = 2
label.en = "Hybrid"

[[uncertainty_scenarios_files]]
id = 0
label.en = "PAR(p)"

[[uncertainty_scenarios_files]]
id = 1
label.en = "Only Ex Ante"

[[uncertainty_scenarios_files]]
id = 2
label.en = "Only Ex Post"

[[uncertainty_scenarios_files]]
id = 3
label.en = "Ex Ante And Ex Post"

[[settlement_type]]
id = -1
label.en = "None"

[[settlement_type]]
id = 0
label.en = "Ex Ante"

[[settlement_type]]
id = 1
label.en = "Ex Post"

[[settlement_type]]
id = 2
label.en = "Dual"

[[make_whole_payments]]
id = 0
label.en = "Constrained On And Off Per Subperiod"

[[make_whole_payments]]
id = 1
label.en = "Constrained on Per Subperiod"

[[make_whole_payments]]
id = 2
label.en = "Constrained on Period Aggregate"

[[make_whole_payments]]
id = 3
label.en = "Ignore"

[[consider_subperiods_loop_for_thermal_constraints]]
id = 0
label.en = "Consider"

[[consider_subperiods_loop_for_thermal_constraints]]
id = 1
label.en = "Do Not Consider"

[[buses_aggregation_for_strategic_bidding]]
id = 0
label.en = "Do Not Aggregate"

[[buses_aggregation_for_strategic_bidding]]
id = 1
label.en = "Aggregate"

[[network_representation]]
id = 0
label.en = "Nodal"

[[network_representation]]
id = 1
label.en = "Zonal"

[[initial_volume_type]]
id = 0
label.en = "Per Unit"

[[initial_volume_type]]
id = 2
label.en = "Volume"

[[intra_period_operation]]
id = 0
label.en = "Reservoir"

[[intra_period_operation]]
id = 1
label.en = "Run of River"

[[demand_type]]
id = 0
label.en = "Inelastic"

[[demand_type]]
id = 1
label.en = "Elastic"

[[demand_type]]
id = 2
label.en = "Flexible"

[[line_model]]
id = 0
label.en = "AC"

[[line_model]]
id = 1
label.en = "DC"

[[price_type]]
id = 0
label.en = "Price Taker"

[[price_type]]
id = 1
label.en = "Price Maker"

[[bid_type]]
id = 0
label.en = "Markup Heuristic"

[[bid_type]]
id = 1
label.en = "Optimize"

[[clearing_subproblem]]
id = 0
label.en = "Ex Ante Physical"

[[clearing_subproblem]]
id = 1
label.en = "Ex Ante Commercial"

[[clearing_subproblem]]
id = 2
label.en = "Ex Post Physical"

[[clearing_subproblem]]
id = 3
label.en = "Ex Post Commercial"

[[commitment_initial_condition]]
id = 0
label.en = "Off"

[[commitment_initial_condition]]
id = 1
label.en = "On"

[[commitment_initial_condition]]
id = 2
label.en = "Undefined"