id = "VirtualReservoir"
icon = "lucide/droplet.svg"
label.en = "Virtual Reservoir"

[[card]]
query = "SELECT COUNT(*) FROM VirtualReservoir"
type = "integer"
label.en = "Elements"
unit.en = "virtual reservoir(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the virtual reservoir"

[[attribute_group]]
id = "owner_and_allocation"
label.en = "Owner and Allocation"
icon = "lucide/user.svg"

[[attribute]]
id = "inflow_allocation"
label.en = "Inflow Allocation"
tooltip.en = "Inflow allocation of the virtual reservoir"

[[attribute]]
id = "assetowner_id"
label.en = "Asset Owner"
tooltip.en = "Asset owner of the virtual reservoir"

[[attribute_group]]
id = "hydro_unit"
label.en = "Hydro Unit"
icon = "lucide/droplet.svg"

[[attribute]]
id = "hydrounit_id"
label.en = "Hydro Unit"
tooltip.en = "Hydro unit of the virtual reservoir"

[[attribute]]
id = "quantity_bid"
label.en = "Quantity Offer"
tooltip.en = "Quantity of bids for virtual reservoirs"
unit.en = "MWh"
hide = true

[[attribute]]
id = "price_bid"
label.en = "Price Offer"
tooltip.en = "Price of bids for virtual reservoirs"
unit.en = "$/MWh"
hide = true
