name = "IARA"
uuid = "8de1ee9a-e440-4915-91b7-d1711c31e0f9"
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingPolyglot = "211639cc-9b11-4cfd-abc6-8f7477829344"
MemoizedSerialization = "a7e9380e-af78-4e01-8a55-c3c07e4c7344"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PSRBridge = "c616c425-6d4e-4525-9781-0810509229d1"
PSRClassesInterface = "1eab49e5-27d8-4905-b9f6-327b6ea666c4"
ParametricOptInterface = "0ce4ce61-57bf-432b-a095-efac525d185e"
PeriodicAutoregressive = "bf9113de-13c2-4ffd-8552-7be908523e05"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Quiver = "cdbb3f72-2527-4dbd-9d0e-93533a5519ac"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
MemoizedSerialization = "0.5.3"
Printf = "1.11.0"
Quiver = "0.1.9"
SDDP = "=1.8.1, 1"
Statistics = "1.11.1"
StatsBase = "0.34.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
